### ISSUE TITLE
build of Pantheios-master\build\vc14 fails

### ISSUE THREAD

**Issue by PhyrexianHulk** [synesissoftware/Pantheios#5]
\Pantheios-master\src\inserters\b64.cpp includes:
/* b64 header files */
#include <b64/b64.h>

b64 directory is not present in \Pantheios-master\include

I ended up having to copy it from b64-1.4.2.zip include directory.

**Comment by PhyrexianHulk** [comment]
the b64 folder is also missing from \Pantheios-master\src

**Comment by synesissoftware** [comment]
Yes, this is a still-current badness in the dependencies that show when building direct from a GH clone/pull. It's because for many years the only way to obtain Pantheios was via the [SourceForge site](https://sourceforge.net/projects/pantheios/)

This issue still remains in the [latest](https://github.com/synesissoftware/Pantheios/releases) - just some moments ago - but will be addressed in the next release.

There're going to be a lot of changes over the next few months, working towards the non-beta release. In the coming weeks we'll sort many/most of these dependency issues.
